name: Update PR on upstream changes once landed on ubuntu
on:
  push:
    paths:
      - '.github/workflows/open-pr-on-changes.yaml'
  schedule:
    - cron: '8 0 * * *'

jobs:
  refresh-upstream:
    name: Check for upstream theme related changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildenv: [
          {
            project: GNOME Shell,
            repo: "https://gitlab.gnome.org/GNOME/gnome-shell.git",
            upstreambranch: main,
            localbranch: gnome-shell,
            projectdir: gnome-shell,
            src: data/theme/,
            dest: gnome-shell/upstream/theme
          },
          {
            project: GNOME Shell Resources,
            repo: "https://gitlab.gnome.org/GNOME/gnome-shell.git",
            upstreambranch: main,
            localbranch: gnome-shell-resources,
            projectdir: gnome-shell,
            src: data/gnome-shell-theme.gresource.xml,
            dest: gnome-shell/upstream/data/gnome-shell-theme.gresource.xml
          },
          {
            project: GNOME Shell Icons,
            repo: "https://gitlab.gnome.org/GNOME/gnome-shell.git",
            upstreambranch: main,
            localbranch: gnome-shell-icons,
            projectdir: gnome-shell,
            src: data/gnome-shell-icons.gresource.xml data/icons,
            dest: gnome-shell/upstream/data/
          },
          {
            project: GTK3,
            repo: "https://gitlab.gnome.org/GNOME/gtk.git",
            upstreambranch: gtk-3-24,
            localbranch: gtk3,
            projectdir: gtk,
            src: gtk/theme/Adwaita/,
            dest: gtk/upstream/gtk-3.0/Adwaita
          },
          {
            project: GTK4,
            repo: "https://gitlab.gnome.org/GNOME/gtk.git",
            upstreambranch: main,
            localbranch: gtk4,
            projectdir: gtk,
            src: gtk/theme/Default/,
            dest: gtk/upstream/gtk-4.0/Default
          },
          {
            project: Libhandy,
            repo: "https://gitlab.gnome.org/GNOME/libhandy.git",
            upstreambranch: main,
            localbranch: libhandy,
            projectdir: libhandy,
            src: src/themes/,
            dest: gtk/upstream/libhandy/themes
          },
          {
            project: Cinnamon,
            repo: "https://github.com/linuxmint/mint-themes.git",
            upstreambranch: master,
            localbranch: cinnamon,
            projectdir: mint-themes,
            src: src/Mint-Y/cinnamon/,
            dest: cinnamon-shell/upstream
          },
      ]
    steps:
      # Checkout code
      - uses: actions/checkout@v3
      - name: Download from ${{ matrix.buildenv.repo }}, on branch ${{ matrix.buildenv.upstreambranch }}
        id: checknewupstream
        run: |
          hasModif="false"
          pushd /tmp
          git clone --branch ${UPSTEAM_BRANCH} --depth 1 ${UPSTREAM_REPO_URL}
          popd
          if [ ${DEST: -1} == '/' ]; then
            mkdir -p ${DEST}
            for src in ${SRC}; do
              rm -rf ${DEST}/src
              cp -a /tmp/${PROJECT_DIR}/${src} ${DEST}
            done
          else
            rm -rf ${DEST}
            cp -a /tmp/${PROJECT_DIR}/${SRC} ${DEST}
          fi
          MODIFIED=$(git status --porcelain)
          if [ -n "$MODIFIED" ]; then
            hasModif="true"
          fi
          echo "::set-output name=modified::${hasModif}"
        env:
          UPSTREAM_REPO_URL: ${{ matrix.buildenv.repo }}
          UPSTEAM_BRANCH: ${{ matrix.buildenv.upstreambranch }}
          SRC: ${{ matrix.buildenv.src }}
          DEST: ${{ matrix.buildenv.dest }}
          PROJECT_DIR: ${{ matrix.buildenv.projectdir }}
      - name: Create or update Pull Request
        if: steps.checknewupstream.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: New upstream snapshot for ${{ matrix.buildenv.project }}
          title: Auto update new upstream snapshot for ${{ matrix.buildenv.project }}
          labels: automated pr, new upstream
          body: "[New upstream ${{ matrix.buildenv.project }} changes](https://github.com/ubuntu/yaru/actions?query=workflow%3A%22Update+PR+on+upstream+changes+once+landed+on+ubuntu%22) by GitHub Action"
          branch: upstream-${{ matrix.buildenv.localbranch }}-update
          token: ${{ secrets.GITHUB_TOKEN }}
